// const SERVER_URL = 'http://3.130.239.232'; // --- Testing
// const SERVER_URL = 'http://18.117.38.42'; // --- DEVELOPER
// const SERVER_URL = 'https://backend-dev.tig.influencesells.com'; // --- UAT
const SERVER_URL = 'https://backend-prod.tig.influencesells.com'; // --- Production

const ADMIN_API_NAME = '/adminapi/';
const USERMANAGEMENT_API_NAME = '/userapi/';
const INFLUENCER_API_NAME = '/influencerapi/';
const BRAND_API_NAME = '/brandapi/';
const CHAT_API_NAME = '/notificationapi/';

const SERVER_URL_ADMIN = SERVER_URL  + ADMIN_API_NAME;
const SERVER_URL_USER_MANAGEMENT = SERVER_URL  + USERMANAGEMENT_API_NAME;
const SERVER_URL_INFLUENCER = SERVER_URL  + INFLUENCER_API_NAME;
const SERVER_URL_BRAND = SERVER_URL  + BRAND_API_NAME;
const SERVER_URL_CHAT_NOTIFICATION = SERVER_URL  + CHAT_API_NAME;

// const SERVER_URL_ADMIN = SERVER_URL + ':3002' + ADMIN_API_NAME;
// const SERVER_URL_USER_MANAGEMENT = SERVER_URL + ':3000' + USERMANAGEMENT_API_NAME;
// const SERVER_URL_INFLUENCER = SERVER_URL + ':3001' + INFLUENCER_API_NAME;
// const SERVER_URL_BRAND = SERVER_URL + ':3003' + BRAND_API_NAME;
// const SERVER_URL_CHAT_NOTIFICATION = SERVER_URL + ':3004' + CHAT_API_NAME;

export {
  SERVER_URL,
  SERVER_URL_USER_MANAGEMENT,
  SERVER_URL_INFLUENCER,
  SERVER_URL_BRAND,
  SERVER_URL_ADMIN,
  SERVER_URL_CHAT_NOTIFICATION
};
